login/urls.py
from django.urls import path

from . import views

app_name = "login"
urlpatterns = [
    path("login.html", views.Login.as_view(), name="login_view"),
    path("logout", views.Logout.as_view(), name="logout"),
    path("cadastro.html", views.Cadastro.as_view(), name="cadastro"),
    path("endereco.html", views.CadastroEndereco.as_view(), name="endereco"),
]

poc_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("produto.urls")),
    path("", include("login.urls")),
]

produto/urls.py
from django.urls import path

from . import views

app_name = "produto"
urlpatterns = [
    path("", views.Produtos.as_view(), name="produtos"),
    path("produto/<int:produto_id>/", views.ProdutoId.as_view(), name="produto"),
    path("finalizar/", views.Compra.as_view(), name="finalizar"),
]

produto/models.py
from django.db import models


class Produto(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=250, help_text="Nome do produto")
    codigo = models.CharField(max_length=250, help_text="Código do produto")
    marca = models.CharField(max_length=250, help_text="Nome da fabricante")
    quantidade_disponivel = models.IntegerField(help_text="Quantidade em estoque")
    valor = models.DecimalField(
        max_digits=20, decimal_places=2, help_text="Valor em BRL"
    )
    data_criado = models.DateTimeField(auto_now_add=True)
    data_alterado = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "produto"
        ordering = ["-id"]
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.nome

produto/forms.py
from django import forms

FORMA_PAGAMENTO_CHOICES = (
    ("1", "Boleto"),
    ("2", "Débito"),
    ("3", "Crédito"),
    ("4", "Pix")
)


class CompraForm(forms.Form):

    quantidade = forms.IntegerField(label="Qtde.", min_value=1)
    marca = forms.CharField(widget=forms.HiddenInput(), required=False)
    codigo = forms.CharField(widget=forms.HiddenInput(), required=False)
    nome = forms.CharField(widget=forms.HiddenInput(), required=False)
    valor = forms.CharField(widget=forms.HiddenInput(), required=False)


class FormaPagamentoForm(forms.Form):

    forma_pagamento = forms.ChoiceField(choices=FORMA_PAGAMENTO_CHOICES)

produto/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, FormView

from .forms import CompraForm, FormaPagamentoForm
from .models import Produto


class Produtos(TemplateView):
    template_name = "produto/produtos.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lista_produtos"] = Produto.objects.all()[:5]
        return context


class ProdutoId(FormView, TemplateView):
    form_class = CompraForm
    template_name = "produto/produto.html"
    success_url = "/finalizar"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["produto"] = Produto.objects.get(id=kwargs["produto_id"])
        return context

    def form_valid(self, form):
        compra = form.cleaned_data
        self.request.session["quantidade"] = compra["quantidade"]
        self.request.session["marca"] = compra["marca"]
        self.request.session["codigo"] = compra["codigo"]
        self.request.session["nome"] = compra["nome"]
        self.request.session["total"] = self.calcula_total(compra)
        return super().form_valid(form)

    def calcula_total(self, compra):
        quantidade = compra["quantidade"]
        valor = compra["valor"].replace(",", ".")
        return str(quantidade * Decimal(valor))


class Compra(LoginRequiredMixin, FormView, TemplateView):
    form_class = FormaPagamentoForm
    login_url = "login:login_view"
    template_name = "produto/finalizar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quantidade"] = self.request.session["quantidade"]
        context["marca"] = self.request.session["marca"]
        context["codigo"] = self.request.session["codigo"]
        context["nome"] = self.request.session["nome"]
        context["total"] = self.request.session["total"]
        return context

produto/templates/produto/finalizar.html
Resumo da compra:

<p>{{ codigo }} {{ nome }}</p>
<p>Marca: {{marca}}</p>
<p>Quantidade: {{quantidade}}</p>
{% load humanize %}
<p>Total: R$ {{total|intcomma}}</p>

<form method="post">
    {% csrf_token %}
    <div id="forma_pagamento">
        <p>Escolha a forma de pagamento:</p>
        <select name="pagamento">
            {% for x,y in form.fields.forma_pagamento.choices %}
                <option value="{{x}}"{% if form.fields.forma_pagamento.value == x %} selected{% endif %}>{{ y }}</option>
            {% endfor %}
        </select>
    </div>
</form>

<p>
    <a href="{{request.META.HTTP_REFERER}}">Voltar</a>
    {% if user.is_authenticated %}
    {% url 'login:logout' as logout_url %}
    <a href="{{ logout_url }}">Logout</a>
    {% endif %}
</p>

produto/templates/produto/header.html
{% if user.is_authenticated %}
    Olá, {{ user.username }}. Aproveite nossos itens.
{% else %}
    Seja bem-vindo(a). <a href="/cadastro.html">Cadastre-se</a> ou <a href="/login.html">entre</a>
    para aproveitar o melhor de nossa loja.
{% endif %}

produto/templates/produto/produto.html
{% include "./header.html" %}

<p>{{ produto.codigo }} {{ produto.nome }}</p>
<p>Marca: {{produto.marca}}</p>
{% load humanize %}
<p>Valor: R$ {{produto.valor|intcomma}}</p>

{% if produto.quantidade_disponivel == 0 %}
<p>Produto fora de estoque</p>
{% else %}
<form method="post">
    {% csrf_token %}
    <div id="compra">
        <p>
            <label for="id_quantidade">Qtde.:</label>
            <input id="id_quantidade" type="number" name="quantidade" min="1" max="{{ produto.quantidade_disponivel }}"
                   required>
            <input id="id_marca" name="marca" type="hidden" value="{{ produto.marca }}">
            <input id="id_codigo" name="codigo" type="hidden" value="{{ produto.codigo }}">
            <input id="id_nome" name="nome" type="hidden" value="{{ produto.nome }}">
            <input id="id_valor" name="valor" type="hidden" value="{{ produto.valor }}">
        </p>
        <input type="submit" value="Adicionar ao carrinho">
    </div>
</form>
{% endif %}

<p>
    <a href="{{request.META.HTTP_REFERER}}">Voltar</a>
    {% if user.is_authenticated %}
    {% url 'login:logout' as logout_url %}
    <a href="{{ logout_url }}">Logout</a>
    {% endif %}
</p>

produto/templates/produto/produtos.html
{% include "./header.html" %}

<p>Escolha seu produto:</p>
{% if lista_produtos %}
    <ul>
    {% for produto in lista_produtos %}
        <li><a href="/produto/{{ produto.id }}/">{{ produto.nome }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não existem produtos cadastrados.</p>
{% endif %}

{% if user.is_authenticated %}
{% url 'login:logout' as logout_url %}
<a href="{{ logout_url }}">Logout</a>
{% endif %}